# Netlify deployment configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build/web"
  command = "if [ ! -d \"flutter\" ]; then git clone https://github.com/flutter/flutter.git --depth 1 -b stable flutter; fi && ./flutter/bin/flutter build web --release --dart-define=VAPID_PUBLIC_KEY=BD9KRxBRpbVGbHeyQu-BlCc74SGzoZCm9vUsy3ukFCNxaFhabmf9XFIV3YkWRJ1sn7XBqpky2snbC2kwgQiQKoY"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
